apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
        - name: server
          image: docker.io/test/go-server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
