name: aliyun cloud service preview
on:
  pull_request:
    paths:
      - '**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: run scripts
        run: /bin/sh test.sh
